.PHONY: drag-force-mover
drag-force-mover:
	python3 drag_force_mover/main.py

.PHONY: friction-mover
friction-mover:
	python3 friction_mover/main.py

.PHONY: force-mass-mover
force-mass-mover:
	python3 force_mass_mover/main.py

.PHONY: force-mover
force-mover:
	python3 force_mover/main.py

.PHONY: mouse-mover
mouse-mover:
	python3 mouse_mover/main.py

.PHONY: mover
mover:
	python3 mover/main.py

.PHONY: vector_mouse
vector_mouse:
	python3 vector_mouse.py

.PHONY: random-vector-generator
random-vector-generator:
	python3 random_vector_generator.py

.PHONY: walker-class
walker-class:
	python3 walker/main.py

.PHONY: walker-with-vector
walker-with-vector:
	python3 walker-with-vector.py

.PHONY: walker
walker:
	python3 walker.py
