.PHONY: mover
mover:
	python3 mover/main.py

.PHONY: vector_mouse
vector_mouse:
	python3 vector_mouse.py

.PHONY: random-vector-generator
random-vector-generator:
	python3 random_vector_generator.py

.PHONY: walker-class
walker-class:
	python3 walker/main.py

.PHONY: walker-with-vector
walker-with-vector:
	python3 walker-with-vector.py

.PHONY: walker
walker:
	python3 walker.py
